	<div class="profile-info">
		<a href="?logout=on" class="button small black" style="color:#FFF; float:right;">Salir</a>
		
		<a href="?logout=on" class="button small black" style="color:#FFF; float:right;margin-right:2px;">No tienes mensajes</a> 
		 
		 
		<h1>{nombre}</h1>
		Brand Ambassador<br/><br/><br/>
		<strong>Progresión del presupuesto</strong>
		
		<br/><br/>
		<div id="profile-budget">
			<img src="{url}img/no-pic.png" align="left" class="profile-img">
			<div style="background-color:#e5e5e5; width:390px; text-align:center; border:1px solid #999; float:left; ">
				<div style="background-color:#FF9900; padding: 43px 0px; width: {budget_used_percentage}; float:left;">{budget_used}€</div>
				<div style="background-color:#efebe2; padding: 43px 0px; width: {budget_ready_percentage}; float:left; ">{budget_ready}€</div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
			
		</div>
		<p>
		<strong>Selección de prendas</strong>
		</p>
			<div id="profile-items">
				<div class="profile-items-name">Tintab hood S</div>
				<div class="profile-items-reference">MS2RDS423</div>
				<div class="profile-items-price">79.95€</div>
				<div class="profile-items-name">Tintab hood S</div>
				<div class="profile-items-reference">MS2RDS423</div>
				<div class="profile-items-price">79.95€</div>
				<div class="profile-items-name">Tintab hood S</div>
				<div class="profile-items-reference">MS2RDS423</div>
				<div class="profile-items-price">79.95€</div>
				<div class="profile-items-name">Tintab hood S</div>
				<div class="profile-items-reference">MS2RDS423</div>
				<div class="profile-items-price">79.95€</div>
				<div class="profile-items-name">Tintab hood S</div>
				<div class="profile-items-reference">MS2RDS423</div>
				<div class="profile-items-price">79.95€</div>
				<div class="clear"></div>
			</div>
	</div>
	<div class="clear"></div>	
