
	<a href="?go=budget&do=new" class="button white" style="padding:10px;">+ Crear presupuesto</a>
<br/><br/>
<table id="myTable" width="100%" class="tablesorter" cellpadding="0" cellspacing="0">
<thead>
<tr>
    <th>ID Presupuesto</th>
    <th>Cliente</th>
    <th>Fecha</th>
    <th>Información</th>
    <th>Opciones</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<br/><br/><center>{page}</center>

