Total pages: [ <b>{total}</b> ]<br/>
<table id="myTable" width="100%" class="tablesorter" cellpadding="0" cellspacing="0">
<thead>
<tr>
    <th>Page</th>
    <th>Advertiser</th>
    <th>Rep</th>
    <th>Size</th>
    <th>Email</th>
    <th>Status</th>
    <th>Options</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<br/>
 
<div class="status no" style="float:right; margin-right:3px;"> Pending </div> 
<div class="status nothing" style="float:right; margin-right:3px;"> Waiting</div> 
<!--<div class="status stanby" style="float:right; margin-right:3px;"> Standby</div> -->
<div class="status change" style="float:right; margin-right:3px;"> Change</div> 
<div class="status ok" style="float:right; margin-right:3px;"> OK</div>

<div class="clear"></div>
<br/><br/><center>{page}</center>

