<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
body{
	font-family: Trebuchet MS, Arial, Helvetica;
	font-size: 10px;
	background-color: #e5e5e5;
}
#content{
	background-color: #FFF;
	border: 1px solid #666;
	width: 398px;
	margin: 0 auto;
}
.main{
	font-size: 14px;
	letter-spacing: -2;
	color: #e5e5e5;
	margin: 0px;
	padding: 0px;
}
-->
</style></head>

<body>
<div id="content">
<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e5e5e5">
<tr>
<td height="500">
<center>
<table width="460" border="0" align="center" cellpadding="0" cellspacing="20" bgcolor="#FFFFFF">
  <tr>
    <td>
    <img src="http://www.socalcommunitypages.com/app/img/car.png" width="150">
    <p>Hello {name},</p>
    <p>Your ad in Socal Community Pages is ready to validate.</p>
    <p>Click the link below to access to your ad :</p>
    <br/>
    <center>{url}</center>
        <p>&nbsp;</p></td>
  </tr>
	<tr>
		<td>
			

		</td>
	</tr>
</table>
</center>
</td>
</tr>
</table>
</div>
</body>
</html>