
	<a href="?go=client&do=new" class="button white" style="padding:10px;">+ Crear nuevo cliente</a>
<br/><br/>
<table id="myTable" width="100%" class="tablesorter" cellpadding="0" cellspacing="0">
<thead>
<tr>
    <th>Nombre</th>
    <th>Compañia</th>
    <th>Email</th>
    <th>Tlf</th>
    <th>Registrado</th>
    <th>Opciones</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<br/><br/><center>{page}</center>

