<div class="dash">
<h3>Control</h3>
<p>{control}</p>
	<div class="graph-testmain" style="height:{week00}px;  margin-top:{margin00}px; background-color:#FF0000;">
	<div class="graph-test" style=" height:{week03}px; {color03} {display03}"><a class="fancybox fancybox.iframe" href="{url00}"> {value03}</a></div>
	<div class="graph-test" style=" height:{week01}px; {color00}"><a class="fancybox fancybox.iframe" href="{url00}"> {value01}</a></div>
	<div class="graph-test" style=" height:{week02}px; {color01} {display0}" ><a class="fancybox fancybox.iframe" href="{url10}">{value02}</a></div>
	Lunes<br/>
	<b>{value00}</b>
	</div>
	
	<div class="graph-testmain" style="height:{week11}px; margin-top:{margin11}px;">
		<div class="graph-test" style=" height:{week13}px; {color03} {display13}"><a class="fancybox fancybox.iframe" href="{url00}"> {value13}</a></div>
		<div class="graph-test" style="height:{week11}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url01}">{value11}</a></div>
		<div class="graph-test" style="height:{week12}px; {color01} {display1}"><a class="fancybox fancybox.iframe" href="{url11}"> {value12}</a></div>
		Martes<br/>
	<b>{value10}</b>
	</div>
	
	<div class="graph-testmain" style="height:{week22}px; margin-top:{margin22}px;">
		<div class="graph-test" style=" height:{week23}px; {color03} {display23}"><a class="fancybox fancybox.iframe" href="{url00}"> {value23}</a></div>
		<div class="graph-test" style="height:{week21}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url02}">{value21}</a></div>
		<div class="graph-test" style="height:{week22}px; {color01} {display2}"><a class="fancybox fancybox.iframe" href="{url12}"> {value22}</a></div>
		Miercoles<br/>
	<b>{value20}</b>
	</div>
	
	<div class="graph-testmain" style="height:{week33}px; margin-top:{margin33}px;">
		<div class="graph-test" style=" height:{week33}px; {color03} {display33}"><a class="fancybox fancybox.iframe" href="{url00}"> {value33}</a></div>
		<div class="graph-test" style="height:{week31}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url03}">{value31}</a></div>
		<div class="graph-test" style="height:{week32}px; {color01} {display3}"><a class="fancybox fancybox.iframe" href="{url13}"> {value32}</a></div>
		Jueves<br/>
	<b>{value30}</b>
	</div>

	<div class="graph-testmain" style="height:{week44}px; margin-top:{margin44}px;">
		<div class="graph-test" style=" height:{week43}px; {color03} {display43}"><a class="fancybox fancybox.iframe" href="{url00}"> {value43}</a></div>
		<div class="graph-test" style="height:{week41}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url04}">{value41}</a></div>
		<div class="graph-test" style="height:{week42}px; {color01} {display4}"><a class="fancybox fancybox.iframe" href="{url14}"> {value42}</a></div>
		Viernes<br/>
	<b>{value40}</b>
	</div>

	<div class="graph-testmain" style="height:{week55}px; margin-top:{margin55}px;">
		<div class="graph-test" style=" height:{week53}px; {color03} {display53}"><a class="fancybox fancybox.iframe" href="{url00}"> {value53}</a></div>
		<div class="graph-test" style="height:{week51}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url05}">{value51}</a></div>
		<div class="graph-test" style="height:{week52}px; {color01} {display5}"><a class="fancybox fancybox.iframe" href="{url15}"> {value52}</a></div>
		Sabado<br/>
	<b>{value50}</b>
	</div>

	<div class="graph-testmain" style="height:{week66}px; margin-top:{margin66}px;">
		<div class="graph-test" style=" height:{week63}px; {color03} {display63} "><a class="fancybox fancybox.iframe" href="{url00}"> {value63}</a></div>
		<div class="graph-test" style="height:{week61}px;  {color00}"><a class="fancybox fancybox.iframe" href="{url06}">{value61}</a></div>
		<div class="graph-test" style="height:{week62}px; {color01} {display6}"><a class="fancybox fancybox.iframe" href="{url16}"> {value62}</a></div>
		Domingo<br/>
	<b>{value60}</b>
	</div>


	<!--<div class="graph" style="height:{week2}px; margin-top:{margin2}px; {color2}"><a class="fancybox" data-fancybox-type="iframe" href="{url2}"> Miercoles<br/>{value2}</a></div>
	<div class="graph" style="height:{week3}px; margin-top:{margin3}px; {color3}"><a class="fancybox fancybox.iframe" href="{url3}"> Jueves<br/>{value3}</a></div>
	<div class="graph" style="height:{week4}px; margin-top:{margin4}px; {color4}"><a class="fancybox fancybox.iframe" href="{url4}"> Viernes<br/>{value4}</a></div>
	<div class="graph" style="height:{week5}px; margin-top:{margin5}px; {color5}"><a class="fancybox fancybox.iframe" href="{url5}"> Sabado<br/>{value5}</a></div>
	<div class="graph" style="height:{week6}px; margin-top:{margin6}px; {color6}"><a class="fancybox fancybox.iframe" href="{url6}"> Domingo<br/>{value6}</a></div>
	<div class="clear"></div>-->
</div>

<div class="dashpanel">
<h3>Resumen semana</h3>
<div class="week">
	<div class="w1">
		Semana
		<h1>{weeks}</h1>
	</div>
	<div class="w2">
		Objetivo semanal 
		<h1>{max}</h1>
	</div>
	<div class="clear"></div>
	<div class="search-week" style="display: none">
		<form method="POST" name="formulario" action="?go=days&do=control">
		{input-week} {input-year} <input type="submit" value="Aceptar">
		</form>
	</div>
</div>
<h3>Progreso</h3>
<div>
{wbar1}
{wbar2}

<div class="clear"></div>
{real_vs_goal}
</div>
<!--<h3>{day}</h3>-->
</div>
<div class="clear"></div>
	
	<div>
	<br/><br/>
	<h3>Objetivo de la semana</h3>
	<p>Esta semana el objetivo es de: <b>{max}</b></p>
	<div class="target">
	{bar}
	</div>
	<div id="downbar">
	{downbar}
	</div>
	<div class="clear"></div>
		 
	</div>
	<div>
	<h3>Objetivo del mes</h3>
	<p>Este mes el objetivo es: <b>{maxmes}</b> {acumuladomes}</p>
		<div class="target">
			{mbar}
		</div>
	{m2}
		<div {class2}>
			{mbar2}
		</div>
	</div>
	
	
	
	<br/><br/>
	<h3>Diario del mes</h3>
<div id="dayafterday">
	
			{dayafterday}
	
	</div>
	
<script>
	$('.w1').click(function() {
			$('.search-week').toggle();
	});
</script>
