
<div class="line">Panel desde el 7 de Junio a 11 de Julio</div>
<div class="col1	">
<h3>Distribución tickets por hora</h3>

{table}
</div>
<div class="col1">
<h3>Ventas / Coste / Beneficios</h3>

<table cellpadding="10	" cellspacing="0" border="0" bgcolor="#e5e5e5" width="100%">
	<tr>
		<td></td>
		<td>Junio</td>
		<td>Julio</td>
		<td>Agosto</td>
		<td>Septiembre</td>
		<td>Total</td>
	</tr>
	<tr>
		<td>Total prendas</td>
		<td>{junioPrendas}</td>
		<td>{julioPrendas}</td>
		<td>{agostoPrendas}</td>
		<td>{septiembrePrendas}</td>
		<td>{TotalPrendas}</td>
		
	</tr>
	<tr>
		<td>Total ventas</td>
		<td>{junioTotalVentas} €</td>
		<td>{julioTotalVentas} €</td>
		<td>{agostoTotalVentas} €</td>
		<td>{septiembreTotalVentas} €</td>
		<td>{TotalVentas} €</td>
		
	</tr>
	<tr>
		<td>Descuento medio</td>
		<td>{junioTotalDesc} %</td>
		<td>{julioTotalDesc} %</td>
		<td>{agostoTotalDesc} %</td>
		<td>{septiembreTotalDesc} %</td>
		<td>{TotalDesc} %</td>
	</tr>
	<tr>
		<td>Descuento ponderado</td>
		<td>{junioDescPonderado} %</td>
		<td>{julioDescPonderado} %</td>
		<td>{agostoDescPonderado} %</td>
		<td>{septiembreDescPonderado} %</td>
		<td>{TotalDescPonderado} %</td>
	</tr>
	<tr>
		<td>Venta real</td>
		<td>{junioVentasDesc} €</td>
		<td>{julioVentasDesc} €</td>
		<td>{agostoVentasDesc} €</td>
		<td>{septiembreVentasDesc} €</td>
		<td>{VentasDesc} €</td>
	</tr>
	<tr>
		<td>Coste</td>
		<td>{juniocoste} €</td>
		<td>{juliocoste} €</td>
		<td>{agostocoste} €</td>
		<td>{septiembrecoste} €</td>
		<td>{coste} €</td>
	</tr>
	<tr>
		<td>IVA</td>
		<td>{junioiva} €</td>
		<td>{julioiva} €</td>
		<td>{agostoiva} €</td>
		<td>{septiembreiva} €</td>
		<td>{iva} €</td>
	</tr>
	<tr>
		<td>Beneficio</td>
		<td>{juniobeneficio} €</td>
		<td>{juliobeneficio} €</td>
		<td>{agostobeneficio} €</td>
		<td>{septiembrebeneficio} €</td>
		<td>{beneficio} €</td>
	</tr>
</table>
</div>

<!--
<div id="wrapper">


	<div id="q2_2010">
	<div id="q1_2010">
	<div id="q4_2009">
	<div id="q3_2009">
	<div id="q2_2009">
	<div id="q1_2005">
		<div id="labels">
			<ul>
				<li><span></span>Internet Explorer</li>
				<li><span></span>Mozilla Firefox</li>
				<li><span></span>Google Chrome</li>
				<li><span></span>Safari</li>
				<li><span></span>Opera</li>
			</ul>
		</div>
		
		
		<div id="percentage_wrapper">
			<div id="percentage">
				<ul>
					<li><p>60.14%</p><p>61.79%</p><p>63.90%</p><p>67.02%</p><p>68.28%</p><p>89.68%</p></li>
					<li><p>24.98%</p><p>24.56%</p><p>24.39%</p><p>23.28%</p><p>23.22%</p><p>6.83%</p></li>
					<li><p>7.14%</p><p>6.03%</p><p>4.27%</p><p>3.08%</p><p>2.35%</p><p>0%</p></li>
					<li><p>5.10%</p><p>4.91%</p><p>4.64%</p><p>4.35%</p><p>3.89%</p><p>2.36%</p></li>
					<li><p>2.66%</p><p>2.73%</p><p>2.52%</p><p>2.29%</p><p>2.27%</p><p>1.15%</p></li>
				</ul>
			</div>
		</div>
		
		<div id="slider">
			<br/><br/>
			<div id="chart_holder">
				<div id="pie_chart">
					<ul>
						<li id="c1_r"><p><span class="pie_left"></span></p></li> 	
						<li id="c1_l"><p><span class="pie_right"></span></p></li>
						<li id="c2_r"><p><span class="pie_left"></span></p></li> 	
						<li id="c2_l"><p><span class="pie_right"></span></p></li>
						<li id="c3_r"><p><span class="pie_left"></span></p></li> 	
						<li id="c3_l"><p><span class="pie_right"></span></p></li>
						<li id="c4_r"><p><span class="pie_left"></span></p></li> 	
						<li id="c4_l"><p><span class="pie_right"></span></p></li>
						<li id="c5_r"><p><span class="pie_left"></span></p></li> 	
						<li id="c5_l"><p><span class="pie_right"></span></p></li>
					</ul>
				</div>
			</div>
		</div>
		<div id="btn_panel">
			<ul>
				<li><a href="#q1_2005"><span>Q1</span><span>2005</span></a></li>
				<li><a href="#q2_2009"><span>Q2</span><span>2009</span></a></li>
				<li><a href="#q3_2009"><span>Q3</span><span>2009</span></a></li>
				<li><a href="#q4_2009"><span>Q4</span><span>2009</span></a></li>
				<li><a href="#q1_2010"><span>Q1</span><span>2010</span></a></li>
				<li><a href="#q2_2010"><span>Q2</span><span>2010</span></a></li>
			</ul>
		</div>
	</div> <!--q1_2005-->
	<!--</div> <!--q2_2009-->
	<!--</div> <!--q3_2009-->
	<!--</div> <!--q4_2009-->
	<!--</div> <!--q1_2010-->
	<!--</div> <!--q2_2010-->
<!--</div>-->

<div class="clear"></div>
<div class="col2">
<h3>Nacionalidades</h3>
<a name="nacional"></a>
{nacional}
</div>
<div class="col2">
<h3>Comparación por mes</h3>
<table cellpadding="10	" cellspacing="0" border="0" bgcolor="#e5e5e5" width="100%">
	<tr>
		<td></td>
		<td>Junio</td>
		<td>Julio</td>
		<td>Total</td>
	</tr>
	<tr>
		<td>Total españoles</td>
		<td>{junioEspanoles}</td>
		<td>{julioEspanoles}</td>
		<td>{TotalEspanoles}</td>
		
	</tr>
	<tr>
		<td>Total extranjeros</td>
		<td>{junioExtranjeros}</td>
		<td>{julioExtranjeros}</td>
		<td>{TotalExtranjeros}</td>
		
	</tr>
</table>
</div>

<div class="clear"></div>
<!--<div class="demo">
<div id="dialog-form" title="Crear una nueva acción">
	<div class="validateTips">Toda la información es requerida.</div>
	<form>
	<fieldset>
		<label for="name">Nombre</label>
		<input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	<fieldset>
		<label for="price">Precio</label>
		<input type="text" name="price" id="price" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	<fieldset>
		<label for="type">Tipo</label>
		<select name="type" id="type">
			<option value="1">Precio por hora</option>
			<option value="2">Precio por unidad</option>
		</select>
	</fieldset>
	<fieldset>
		<input type="hidden" name="id" id="id" value="{id}"/>
	</fieldset>
	</form>
</div>



<button id="create-user">Cargar Excel</button>-->

