<div class="col" style="{color}">
	<div class="cel"> {col_mes}</div>
	<div class="cel"> {col_prendas}</div>
	<div class="cel"> {col_num_tickets}</div>
	<div class="cel"> {col_items_per_ticket}</div>
	<div class="cel"> {col_ticket_medio}</div>
	<div class="cel"> {col_ventas}</div>
	<div class="cel"> {col_total_desc}</div>
	<div class="cel"> {col_ponderado_desc}</div>
	<div class="cel"> {col_ventas_desc}</div>
	<div class="cel"> {col_coste}</div>
	<div class="cel"> {col_iva}</div>
	<div class="cel"> {col_beneficio}</div>
</div>