<div class="col_">
	{menu}
	<div class="col21">
		<h3>Distribución tickets por hora</h3>
		{table}
		
		<h3>Distribución de edades</h3>
		{edades}
		
		
	</div>

	
	<div class="col21">
		<h3>Distribución sexo</h3>
		{sexo}
		<h3>Nacionalidades</h3>
		<a name="nacional"></a>
		{nacional}
	</div>
	<div class="clear"></div>
</div>


<div class="col1">
<h3>Ventas / Coste / Beneficios</h3>


<div class="col">
	<div class="cel"> <b>MES</b></div>
	<div class="cel"> <b>Nº PRENDAS</b></div>
	<div class="cel"> <b>Nº DE TICKETS</b></div>
	<div class="cel"> <b>Nº DE ITEMS POR TICKET</b></div>
	<div class="cel"> <b>TICKET MEDIO</b></div>
	<div class="cel"> <b>VENTAS</b></div>
	<div class="cel"> <b>DESC MEDIO</b></div>
	<div class="cel"> <b>DESC PONDERADO</b></div>
	<div class="cel"> <b>VENTA REAL</b></div>
	<div class="cel"> <b>COSTE</b></div>
	<div class="cel"> <b>IVA</b></div>
	<div class="cel"> <b>BENEFICIO</b></div>
</div>
{col}
</div>



<div class="clear"></div>



