<div class="dash">
{alert}
<h3>Espa&ntildeoles vs Extranjeros</h3>
{bar2}


<h3>Estadistica de compradores</h3>

{bar}
</div>


<div class="dash-control">
<h3>Busqueda</h3>
<form method="post" name="control" action="?go=days&do=stats&form=1">
Desde: <br/><input class="dash-control-input" name="begin" type="date"><br/>
Hasta: <br/><input class="dash-control-input" name="end" type="date"><br/>

<br/>
<br/>
<input type="submit" value="Aceptar" class="dash-control-input">
</form>
</div>


</div>
<div class="clear"></div>
	
	