<tr> 
	<td><input type="checkbox" name="select[]" value="{id}" {checked}></td>    
    <td>
    <span class="template-links"><strong>
    <div class="edit" id="div_1"><a href="{url1}">{data1}</a></div></strong></span></td>  
    <td>{data2}</td>
    <td>{data3}</td>
    <td>{data4}</td> 
	<td>{data5}</td>
    <td>
    	<a href="{url3}"  class="button red" onclick="return confirmar()">X</a>

    </td> 
</tr>