<a href="?go=user&do=new" class="button white" style="padding:10px;">+ Crear nuevo usuario</a>
<br/><br/>
<table id="myTable" width="100%" class="tablesorter" cellpadding="0" cellspacing="0">
<thead>
<tr>
    <th>Nombre de usuario</th>
    <th>Email</th>
    <th>Registrado</th>
    <th>Última vez</th> 
    <th>Opciones</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>

<span style="font-size:10px; padding-top:40px;"><b>***</b> Super Admin</span><br/>
<span style="font-size:10px; padding-top:40px;"><b>**</b> Admin</span><br/>
<span style="font-size:10px; padding-top:40px;"><b>*</b> Editor</span><br/>