<form id="auth" method="post" action="{action}">
	<div class="login-data"><b>USERNAME</b><br/>
		<div class="login-subtext">Introduzca su nombre de usuario</div>
	</div>
	<input type="text" name="user" class="login-form">
	<div class="login-data"><b>PASSWORD</b><br/>
		<div class="login-subtext">Introduzca su clave de acceso</div>
	</div>
	<input type="password" name="pass" class="login-form">
	<div align="right"><input type="submit" value="Entrar"></div>
</form>
