<div class="clear"></div>
<div class="profile-items-edit">
	<form method="post" action="?go=profile&submit=edit&id={id_BA}" id="formedit">
		<input type="text" name="name" value="{name}" class="edit-form">
		<input type="text" name="reference" value="{reference}" class="edit-form">
		<input type="text" name="value" value="{value}" class="edit-form">
		<input type="text" name="size" value="{size}" class="edit-form">
		<input type="hidden" name="id_item" value="{id}">
		<a href="#" id="edit" class="button black">Editar</a>
	</form>
</div>