<div class="news-ncomment"><iframe src="http://www.facebook.com/plugins/like.php?href=http://www.fernandosalom.es{url}&amp;layout=box_count&amp;show_faces=false&amp;width=100&amp;action=like&amp;colorscheme=light&amp;height=65" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:65px;" allowTransparency="true"></iframe></div>

<div id="scrollpages"> 
   	<a href="{url}#to-comment">Quiero Comentar!</a>
</div>

<div class="clear">	</div>
          		

<div class="news-info">Escrito por {author} | {date}</div>       		
<div class="news-line"></div>
<div class="news-sentence"><a href="{url}">{content}</a></div>


<br/>
<div id="to-comments"></div>