			<div id="info">
				<h1>{title}</h1>
				<div class="col2">{col1}
				</div>
				<div class="col2">{col2}
				</div>
			</div>
			<div id="info_menu">
				<h2>Que hacemos</h2>
				<ul>
					<li><a href="#">Ganadería</a></li>
					<li><a href="#">Formación</a></li>
					<li><a href="#">Biocombustible</a></li>
					<li><a href="#">Producción</a></li>
					<li><a href="#">Consultoría</a></li>
					<li><a href="#">Visitas guiadas</a></li>
				</ul>
			</div>
