<!--
<div id="to-comment"></div>
<div id="new-add"></div>
<span id="new-comment-comment"></span>
<div class="space"></div>
<form action="{comment_action}" method="post">
<div id="new-comment"><br/>
	<h1>Añade tu comentario</h1><br/>
	Me reservo el derecho de eliminar y/o modificar aquellos comentarios que se salgan de esta temática , así como los promocionales (spam), susceptibles de afectar a derechos de terceros o de vulnerar las leyes. <br/>
	Lenguaje HTML permitido : <b>strong , em , a , ul , li , i , u</b>
	<br/><br/>
	<div class="new-comment-textarea">
		<label for="comment">Comentario</label> <strong title="OBLIGATORIO" class="news-required">*</strong> :<br />
		<textarea name="comment" id="comment"></textarea>
	</div>

	<div class="new-comment-fields">
		<label for="author">Nombre</label> <strong title="OBLIGATORIO" class="news-required">*</strong> :
		<input type="text" name="author" id="author" class="new-comment-input" value="{name}"/>
		<label for="email">Email</label> <strong title="OBLIGATORIO" class="news-required">*</strong> <span class="news-comment-info">(no será publicado) </span>:
		<input type="text" name="email" id="email" class="new-comment-input" value="{mail}"/>
		<label for="web">Web</label>  :
		<input type="text" name="web"  id="web"class="new-comment-input" value="{web}"/>
	</div>



<input type="button" value="Enviar comentario" id="sendcomment">
</div>
</form>
-->