<div id="news-date"> 
   	<span class="news-day">{day}</span><br/>
   	<span class="news-year">{month} {year}</span>
</div>
<div class="news-ncomment"><strong>{comment}</strong></div>
<br/>
<div class="clear"></div>
<h1><a href="{url}">{title}</a></h1>          		
<div class="news-line"></div>
<div class="news-content">
{content1}
</div>
<div align="right"><div class="more"><strong>{more}</strong></div></div>
<br/><br/>
<div class="line"></div>

