<p><strong>
	En Grupo San Ramón tenemos la fuerte convicción de que para poder aprender hay que ver como son las cosas y como funcionan. 
</strong></p>
<p>
Es por ello que ofrecemos la posibilidad de visitar nuestras instalaciones y hacer una ruta turística por alrededor y por el interior de la granja ya sea por ocio, visitas o formación.
</p>
<p>
	Para aquellos que no nos conozcan somos una de las granjas más grandes a nivel europeo con más de 35 años de experiencia y con alrededor de 2200 vacas a las que cuidamos con sumo cuidado para que se encuentren en las mejores condiciones posibles ya que sabemos que la calidad de la leche depende no solo del alimento de la vaca sino también de su descanso, cuidado e higiene.
	
</p>
<p>
	Nuestras instalaciones se encuentran muy cerca de Requena en un entorno de más de 1.000.000m2 formado por numerosos edificios entre los que se encuentran:
	<ul>
	<li>5 Naves de descanso para nuestras vacas.</li>
	<li>1 Nave de ordeño</li>
	<li>Planta de Biogas</li>
	<li>Instalaciones suplementarias</li>
	<li>Oficinas</li>
	</ul>
	Y mucho más
</p>
<p>
	
</p>