<p><strong>
	Toda una saga de Ganaderos. Tres generaciones han vivido y viven dedicadas al mundo de la leche, desde sus inicios en los años 40 hasta la actualidad.
</strong></p>

<p>
	Es en los 70 cuando su fundador, Don Ramón Garcerá Esteve, decide dar un cambio radical a lo que, hasta entonces, había sido la ganadería tradicional en su casa. Con 20 vacas lecheras comenzaría lo que hoy es el actual Grupo San Ramon dirigido por la propia familia. Todo un reto dentro del sector ganadero, inmerso en una restructuración constante de modernización e investigación.
</p>

<p>
	Durante 35 años la Granja San Ramón ha crecido en sus anteriores instalaciones, hasta alcanzar un total de 2.000 cabezas de ganado lechero; iniciando procesos de fabricación propia de alimentos; y consiguiendo, día a día, la excelencia en el trabajo y la trazabilidad en todos sus procesos, llegando a ser, en su sector, la primera empresa que consigue trabajar con la ISO 9001. De la misma forma, diferentes premios del sector ponen de manifiesto su hecho más diferenciador: la innovación.
</p>