<img src="modules/home/img/entrada2.jpg">
<p>
Estas visitas guiadas se adaptan según el público tengamos pudiendo ser orientadas a estudiantes, universitarios o profesionales dependiendo de las necesidades de cada grupo.
</p>
<p>
Si deseas realizar una visita a nuestra granja ponte en contacto con nosotros en cualquier momento estaremos encantados de atenderte y ayudarte en todo lo que necesites.
</p>
<p>
<div class="visit">
	<a href="contactar/">
		Anímate visítanos y disfruta de la experiencia
	</a>
</div>
</p>