<h1>Contactar</h1>
<p>La información necesaria para poder ponerse en contacto con nosotros en el momento que desee es la siguiente:<br/>
<strong>Dirección:</strong> Finca la Bonora, Campo Arcís, 46340 - Requena, Valencia<br/>
<strong>Teléfono: </strong> 96 233 81 70<br/>
<strong>Fax:</strong> 96 233 81 68 <br/>
</p>
<p>Si desea contactar con nosotros por email, rellene los siguientes datos y nos pondremos en contacto con usted lo antes posible</p>
<div id="form">
<form method="post" action="?go=contact&do=send">
	<div class="formLine">
	<div class="content">Nombre (requerido) :</div>
	<input type="text" name="nombre" class="input">
	</div>
	<div class="formLine">
	<div class="content">Correo electrónico (requerido) :</div>
	<input type="text" name="email" class="input">
	</div>
	<div class="formLine">
	
	<div class="content">Comentario :</div>
	<textarea name="comentario" rows="10" class="input"></textarea>
	</div>
	
	<input type="submit" value="Enviar" class="submit">
	<div class="clear"></div>
</form>
</div>