<p><strong>
Nuestro principal trabajo durante todos estos años es y será la ganadería. Hemos dedicado más de 35 años al cuidado de la leche y de las vacas que estas producen mejorando día a día los procesos necesarios para ello.
</strong></p>

<p>
Nuestro apartado de ganadería se divide en varias unidades de negocio distribuidas de la siguiente manera:
</p>
<p><strong>Vacas</strong><br/>
2.200 vacas de alta genética en producción constante, hace de nuestra empresa una de las mas modernas y mayores productoras de leche del país. Las vacas son alojadas en unas instalaciones de última generación desarrolladas específicamente para proporcionarles el mayor posible. Para ello las instalaciones constan de: colchones de goma para su descanso diario , amplias y confortables habitaciones individuales, agua y comida en sus respectivas zonas, sistemas robotizados de limpìeza para que siempre dispongan de la máxima higiene y confort.</p>

<p><strong>Ordeño</strong><br/>
Nuestra sala de ordeño posee la mayor tecnología disponible. Para ello todas las vacas llevan 2 tipos de identificaciones electrónicas, las cuales hacen que podamos tenerlas identificadas vía antenas electrónicas comunicadas con sus respectivos ordenadores que analizan la información y a su vez controlan nuestra sala de ordeño. Este sistema permite tener 80 vacas ordeñando al mismo tiempo y a la vez garantía la higiene y salubridad su leche.
</p>
<center>
<img src="modules/home/img/descanso.jpg">
</center>
