			<div id="info">
				<h1>{title}</h1>
				<div class="col2">{col1}
				</div>
				<div class="col2">{col2}
				</div>
			</div>
			<div id="info_menu">
				<h2>Qué hacemos</h2>
				<ul>
					<li><a href="que-hacemos/">Ganadería</a></li>
					<li><a href="formacion/">Formación</a></li>
					<li><a href="biocombustible/">Biogás</a></li>
					<li><a href="produccion/">Producción</a></li>
					<li><a href="consultoria/">Consultoría</a></li>
					<li><a href="visitas-guiadas/">Visitas guiadas</a></li>
					<li><a href="eventos/">Eventos</a></li>
				</ul>
			</div>
