			<div id="info">
				<h1>{title}</h1>
				<div class="col2">{col1}
				</div>
				<div class="col2">{col2}
				</div>
			</div>
			<div id="info_menu">
				<h2>Formatos bolsas</h2>
				<center>
					<a href="img/bolsa/bolsa1x.jpg"><img src="img/bolsa/bolsa1.jpg" class="img_sustrato"></a>
					<a href="img/bolsa/bolsa3x.jpg"><img src="img/bolsa/bolsa3.jpg" class="img_sustrato"></a>

				</center>
			</div>
