<center>
<img src="modules/home/img/ganaderia.jpg">
</center>
<p><strong>Terneros</strong><br/>
Cada año hacemos la recría de 500 terneros machos para la venta a terceros y posterior engorde para carne, todos estos terneros son criados hasta los 21 días de vida en nuestras instalaciones y cuidados con un mimo especial, son alimentados con un sistema robotizado que les aporta la cantidad necesaria de leche, agua y pienso en el momento del día que lo demanda. Del mismo modo criamos 500 terneras que se quedaran en la explotación para hacer el relevo generacional de sus madres en un futuro de 2 años vista.
</p>

<p><strong>Novillas</strong>
Siempre hemos sido un referente en el mundo de la genética, de tal manera que hace 25 años que toda la Inseminación de sus animales es Artificial, de modo que el aumento genético de sus animales ha tenido una velocidad de crucero constante y en aumento. Todos los animales son catalogados y puntuados en la explotación, creando una base de datos con la cual elegimos los mejores sementales para acoplar en la inseminación y poder obtener una cría que supere a la madre en producción y tipo. Todo esto se lleva a cabo bajo la supervisión de los técnicos veterinarios, al igual que el control de los procesos de vacunación y bienestar de los animales durante el tiempo que dura su recría en la explotación.
</p>