<p><strong>
En Granja San Ramón siempre nos hemos preocupado por el impacto en el entorno de nuestra actividad. Con el objetivo de reducirlo al mínimo, se apostó desde el primer momento por la instalación de una planta de biogás para el aprovechamiento del estiércol de los animales de la explotación.
</strong></p>

<p>
Este sistema permite mediante un proceso de biometanización, o digestión anaerobia, la obtención de biogás que se utiliza para la generación de energía eléctrica. El estiércol es recogido de manera automática de las naves de estabulación y bombeado hasta la propia planta. Además del estiércol propio, se introducen otras materias para realizar una codigestión. Con ello se aumenta el rendimiento del proceso y además, indirectamente, se reduce el impacto de otras actividades sobre el medio ambiente. 
</p>
<p>
Así pues, además de reducir el impacto de los efluentes se consigue una serie de efectos que convierten al biogás en una de las grandes alternativas en el sector ganadero tales como:
</p>


