	Los efectos que el sustrato produce sobre la planta son:
<ul>
<li>Aumento del color y del brillo</li>
<li>Fortalecimiento de las raíces</li>
<li>Acelera el desarrollo y el crecimiento de la planta</li>
<li>Aumento del tamaño de frutos y semillas</li>
<li>Resistencia a plagas y enfermedades</li>
</ul>
<p>	Y será así desde el primer al último kilogramo, ya que durante el proceso de fabricación se lleva un control exhaustivo del proceso y las características del producto, de modo que la trazabilidad es absoluta y se puede asegurar la mayor calidad del sustrato fertilizante FBO de Grupo San Ramón.
</p>
<div class="info-sustrato">
<strong>Contacto para pedidos:</strong>
Bernat Chuliá Peris</br>
Tlf: 628093974</br>
E-mail: <a href="mailto:bernat@gruposanramon.com">bernat@gruposanramon.com</a></br>
</div></br>
<div class="info-sustrato">
<strong>FBO Sustrato fertilizado<br/>
SUSTRATO DE CULTIVO - COMPOST </strong>
<p>100% a partir de material de digestión del tratamiento anaeróbio de residuos animales y vegetales
Materia Orgánica: 60% sobre materia seca</p>
<ul>
<li>pH: 7’5 - 8’5</li>
<li>Conductividad (dS/m): 3-5</li>
<li>Extracto húmico (%): 7</li>
<li>C/N: 10</li>
<li>Clase A. Contenido en metales pesados inferior a los límites autorizados para esta clasificación.</li>

</ul>
</div><br/>
<div class="info-sustrato">
<strong>Etiquetas de sustrato fertilizado</strong>
<p>FORMATOS</p>
<ul>
<li>1 litro</li>
<li>3 litros</li>
<li>5 litros</li>
<li>10 litros</li>
</ul>
</div>

