<p><strong>
¿Alguna vez ha necesitado de una ubicación en la que poder realizar un evento ya sea una reunión con clientes, un programa formativo, promociones... etc?. Grupo San Ramón pone a su disposición sus instalaciones para ello.
</strong></p>
<center>
<img src="modules/home/img/entrada2.jpg">
</center>
<p>
Situada en la Comarca de Utiel-Requena, encontramos esta finca inigualable con 100 Ha. de terreno convertido en una moderna y ecológica granja de vacas, que pone a tu disposición sus instalaciones para numerosos eventos, en el entorno más adecuado para conseguir tus objetivos.
</p>

<p>
Grupo San Ramón dispone de las instalaciones necesarias para dar el mejor servicio para eventos de tipo:
</p>
<ul>
	<li>Corporativos
		<ul>
			<li>Comités de dirección</li>
			<li>Reuniones de trabajo</li>
			<li>Presentación de productos</li>
			<li>Presentación de empresas</li>
			<li>Eventos para la fidelización de clientes</li>
		</ul>
	</li>
	<li>Promocionales
		<ul>
			<li>Lanzamiento de productos</li>
			<li>Demostraciones</li>
			<li>Campañas publicitarias</li>
			<li>Promociones</li>
		</ul>
	</li>
	<li>Formación
		<ul>
			<li>Charlas</li>
			<li>Cursos</li>
			<li>Jornadas</li>
			<li>Seminarios</li>
		</ul>
	</li>
	<li>Relaciones públicas
		<ul>
			<li>Ruedas de prensa</li>
			<li>Reuniones con los medios</li>
		</ul>
	</li>
	<li>Visitas con clientes y proveedores</li>
</ul>
