
<center>
<img src="modules/home/img/biogas.png">
</center>

<ul>
<li>Reducción de las emisiones de CO2, al reducir las emisiones de metano.</li>
<li>Gestión de residuos agroalimentarios propios o ajenos en codigestión.</li>
<li>Generación de energía eléctrica a partir de una fuente renovable.</li>
<li>Generación de energía térmica por cogeneración.</li>
</ul>
<p>
Si estás interesado en conocer las instalaciones o en recibir asesoramiento sobre temas relacionados con el biogás, ponte con contacto con nosotros a través del formulario de contacto indicando los temas de interés o suscríbete a nuestra newsletter para recibir información periódica de cursos y noticias sobre Grupo San Ramón.
</p>