<p><strong>
Grupo San Ramón pone su conocimiento a disposición de todo aquel que quiera mejorar o conocer los métodos de gestión del biogas, pilotaje de nuevos sustratos a digestionar ...
</strong></p>

<p>
Durante más de 35 años hemos estado adquiriendo conocimientos que nos han llevado a ser una de las granjas más importantes de España, para ello hemos tenido que seguir un duro camino de constante innovación para estar siempre un paso por delante del mercado. Ahora hemos decidido compartir este conocimiento a través de nuestro departamento de consultoría
</p>
<p>
Nuestro departamento de consultoría esta formado por un grupo de expertos con dilatada experiencia en el sector de la ganadería, plantas de biogás, pilotajes de nuevos sustratos a digestionar y un largo número de campos relacionados con la ganadería.
</p>

