<center>
<img src="img/producto.jpg">
</center>
<p><strong>
El sustrato fertilizado FBO de Grupo San Ramón, es un sustrato a partir de compost orgánico con un alto contenido en materia orgánica. Se trata de un producto único en el mercado al proceder de una planta de biogás, ya que este proceso le otorga una serie de propiedades diferenciadoras del resto de productos.
</strong></p>
<p>	Además del elevado contenido en materia orgánica, es capaz de aportar los principales nutrientes (Nitrógeno, Fósforo, Potasio...) y los microelementos necesarios. También posee un destacable contenido en ácidos fúlvicos y húmicos que completan las necesidades nutritivas de la planta. La presencia de fibras vegetales favorece la retención y distribución del agua, y con ello la absorción de los nutrientes. </p>

<p>	El proceso de producción evita la presencia de semillas y cuerpos extraños en el producto. Además, junto con la higienización y desinfección del producto, se consigue una ausencia total del olor que permite utilizarlo en cualquier apliación doméstica. </p>

<p>	Así pues, el sustrato fertilizado está indicado como complemento para:</p>

<ul>
<li>Plantas de interior</li>
<li>Plantas de exterior</li>
<li>Huertos urbanos y domésticos</li>
<li>Árboles frutales</li>
</ul>
<p>	Suponiendo en todos los casos una ventaja ya que no hay necesidad de aportar ningún tipo de fertilizante químico artificial para un correcto desarrollo de la planta.</p>


