<p>
Entre las instalaciones que grupo San Ramón le ofrece se encuentra el alquiler de un aula multifuncional desde la que sentirá la armonía del paisaje que le rodea.</p>
<p>
Este aula esta especialmente adecuada para eventos de formación, reuniones, comidas de trabajo, entrevistas, selecciones de personal etc. El equipamiento de esta sala esta compuesto por:	</p>
<ul>
	<li>Climatización</li>
	<li>15 mesas de trabajo</li>
<li>1 puesto de docente</li>
<li>Proyector</li>
<li>Conexión a internet inalambrica</li>
<li>Televisión</li>
<li>Pizarra</li>
<li>Cocina (microondas, frigorífico y cafetera expreso)</li>
<li>Aseo</li>
<li>Terraza</li>
</ul>
<center>
<a href="modules/home/img/casa2.png"><img src="modules/home/img/casa.png" border="0"></a>
</center>

<p>El horario de disponibilidad de este aula es de 08:30 a 19:30 y cuenta con un aforo máximo de 15 personas.</p>

<p>El alquiler de este aula es <b>50 euros/hora*</b>. Adicionalmente Grupo San Ramón ofrece un servicio de cofee break** por <b>10 euros/persona*</b></p>

<p>* Los precios no incluyen IVA<br/>
** El servicio de cofee break consiste en: café, leche, zumos de frutas, selección de mini bollería recién hecha y agua.
</p>
