<h1>Localización</h1>
<p></p>
<div id="map">
	<center><a href="../modules/home/face/mapa_grande.jpg"><img src="../modules/home/face/mapa.jpg"></a></center>
<!--<iframe width="690" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.es/maps/ms?ie=UTF8&amp;hl=es&amp;msa=0&amp;msid=210141151561708862481.00049da078350b9beced9&amp;ll=39.419718,-1.141548&amp;spn=0,0&amp;t=h&amp;output=embed"></iframe><br /><small>Ver <a href="http://maps.google.es/maps/ms?ie=UTF8&amp;hl=es&amp;msa=0&amp;msid=210141151561708862481.00049da078350b9beced9&amp;ll=39.419718,-1.141548&amp;spn=0,0&amp;t=h&amp;source=embed" style="color:#0000FF;text-align:left">Grupo San Ramón</a>-->
</div>