<div id="template-login">
<form id="auth" method="post" action="{action}">
	<div class="login-data"><b>USERNAME</b><br/>
		<div class="login-subtext">Introduzca su nombre de usuario</div>
	</div>
	<input type="text" name="user" class="login-form">
	<div class="clear"></div>
	<div class="login-data"><b>PASSWORD</b><br/>
		<div class="login-subtext">Introduzca su clave de acceso</div>
	</div>
	<input type="password" name="pass" class="login-form">
	
	<input type="submit" value="Entrar" class="login-button">
	<div class="clear"></div>
</form>
</div>
